### ISSUE TITLE
Compile with EP32:3.3.3 using Arduino IDE NV error

### ISSUE THREAD

**Issue by chemistorge** [hjd1964/OnStepX#105]
Hi, 

I cannot compile onstepx on a DOIT ESP32 DEV KIT V1: I always get these errors: 

NvBase.cpp.o:(.rodata._ZTV18NonVolatileStorage[_ZTV18NonVolatileStorage]+0x1c): undefined reference to `_ZN18NonVolatileStorage14writeToStorageEth'

And:

NvBase.cpp.o:(.rodata._ZTV18NonVolatileStorage[_ZTV18NonVolatileStorage]+0x18): undefined reference to `_ZN18NonVolatileStorage15readFromStorageEt'

Am I missing a config change?
